# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ce403cf36e617b8c88f9bdfb86dff6860e433dc5a5696dde78c714a0031e892195085d260bf9ba4d553e082083b366f4c9aea7e4e334fa7f12d8d7328e0a688

test:
  secret_key_base: e3be776f5320d352a6c1f1d147f0b414d6f80cb0cdcd477dfab94455f94c9dd52e115ef92cfaf9b728c079b60e3d23c261e26b5db30bdb7eca9f42dbefa73af7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
