toolbar:
  - fontselect | fontsizeselect | bold italic underline | alignleft aligncenter alignjustify alignright
  - bullist | numlist | outdent | indent | forecolor | backcolor | undo | redo | link | unlink

menubar: false

plugins:
  - link
  - paste
  - importcss
  - autolink
  - lists
  - wordcount
  - colorpicker
  - textcolor

height : "250"